begin;

create schema if not exists myappdb;

create table if not exists myappdb.suplidores (
  id integer generated by default as identity primary key,
  codigo text not null,
  nombre_comercial text not null,
  contacto text,
  tipo_documento text not null default 'RNC',
  numero_documento text not null,
  telefono text,
  correo text,
  direccion text,
  ciudad text,
  categoria text not null default 'Local',
  condiciones_pago text,
  balance numeric(14, 2) not null default 0,
  estado text not null default 'Activo',
  ultima_orden text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint suplidores_codigo_key unique (codigo),
  constraint suplidores_numero_documento_key unique (numero_documento),
  constraint suplidores_tipo_documento_check check (tipo_documento in ('RNC', 'Cedula', 'Pasaporte')),
  constraint suplidores_categoria_check check (categoria in ('Local', 'Importador', 'Servicios')),
  constraint suplidores_estado_check check (estado in ('Activo', 'Inactivo', 'Suspendido'))
);

create index if not exists suplidores_nombre_comercial_idx on myappdb.suplidores (nombre_comercial);
create index if not exists suplidores_contacto_idx on myappdb.suplidores (contacto);
create index if not exists suplidores_categoria_idx on myappdb.suplidores (categoria);
create index if not exists suplidores_estado_idx on myappdb.suplidores (estado);

create or replace function myappdb.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'suplidores_set_updated_at'
      and tgrelid = 'myappdb.suplidores'::regclass
  ) then
    create trigger suplidores_set_updated_at
    before update on myappdb.suplidores
    for each row
    execute function myappdb.set_updated_at();
  end if;
end;
$$;

alter table myappdb.suplidores enable row level security;

grant usage on schema myappdb to anon, authenticated, service_role;
grant select, insert, update, delete on myappdb.suplidores to anon, authenticated, service_role;
grant usage, select on sequence myappdb.suplidores_id_seq to anon, authenticated, service_role;
grant execute on function myappdb.set_updated_at() to anon, authenticated, service_role;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'suplidores'
      and policyname = 'suplidores_select_local_app'
  ) then
    create policy "suplidores_select_local_app"
    on myappdb.suplidores
    for select
    to anon, authenticated
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'suplidores'
      and policyname = 'suplidores_insert_local_app'
  ) then
    create policy "suplidores_insert_local_app"
    on myappdb.suplidores
    for insert
    to anon, authenticated
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'suplidores'
      and policyname = 'suplidores_update_local_app'
  ) then
    create policy "suplidores_update_local_app"
    on myappdb.suplidores
    for update
    to anon, authenticated
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'suplidores'
      and policyname = 'suplidores_delete_local_app'
  ) then
    create policy "suplidores_delete_local_app"
    on myappdb.suplidores
    for delete
    to anon, authenticated
    using (true);
  end if;
end;
$$;

commit;
