begin;

create schema if not exists myappdb;

create sequence if not exists myappdb.factura_numero_seq
  start with 1
  increment by 1;

create table if not exists myappdb.facturas (
  id bigint generated by default as identity primary key,
  numero_factura text not null unique default ('FAC-' || lpad(nextval('myappdb.factura_numero_seq')::text, 6, '0')),
  cliente_id integer,
  cliente_nombre text not null,
  cliente_rnc text,
  cliente_telefono text,
  cliente_correo text,
  cliente_direccion text,
  cliente_ciudad text,
  fecha_factura date not null default current_date,
  tipo_ncf text,
  ncf text,
  condicion_pago text not null default 'Contado',
  notas text,
  subtotal numeric(14, 2) not null default 0,
  itbis numeric(14, 2) not null default 0,
  total numeric(14, 2) not null default 0,
  estado text not null default 'Emitida',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint facturas_condicion_pago_check check (condicion_pago in ('Contado', 'Credito')),
  constraint facturas_estado_check check (estado in ('Emitida', 'Anulada')),
  constraint facturas_totales_check check (subtotal >= 0 and itbis >= 0 and total >= 0)
);

create table if not exists myappdb.factura_detalles (
  id bigint generated by default as identity primary key,
  factura_id bigint not null references myappdb.facturas(id) on delete cascade,
  producto_id integer,
  codigo_producto text,
  descripcion text not null,
  cantidad numeric(14, 2) not null,
  precio_unitario numeric(14, 2) not null,
  tasa_itbis numeric(5, 2) not null default 0,
  monto_itbis numeric(14, 2) not null default 0,
  total_linea numeric(14, 2) not null,
  creado_en timestamptz not null default now(),
  constraint factura_detalles_cantidad_check check (cantidad > 0),
  constraint factura_detalles_precio_check check (precio_unitario >= 0),
  constraint factura_detalles_itbis_check check (tasa_itbis >= 0 and tasa_itbis <= 100),
  constraint factura_detalles_total_check check (monto_itbis >= 0 and total_linea >= 0)
);

create index if not exists facturas_fecha_factura_idx on myappdb.facturas (fecha_factura desc);
create index if not exists facturas_cliente_id_idx on myappdb.facturas (cliente_id);
create index if not exists facturas_ncf_idx on myappdb.facturas (ncf);
create index if not exists factura_detalles_factura_id_idx on myappdb.factura_detalles (factura_id);

create or replace function myappdb.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'facturas_set_updated_at'
      and tgrelid = 'myappdb.facturas'::regclass
  ) then
    create trigger facturas_set_updated_at
    before update on myappdb.facturas
    for each row
    execute function myappdb.set_updated_at();
  end if;
end;
$$;

alter table myappdb.facturas enable row level security;
alter table myappdb.factura_detalles enable row level security;

grant usage on schema myappdb to anon, authenticated, service_role;
grant select, insert, update, delete on myappdb.facturas to anon, authenticated, service_role;
grant select, insert, update, delete on myappdb.factura_detalles to anon, authenticated, service_role;
grant usage, select on sequence myappdb.facturas_id_seq to anon, authenticated, service_role;
grant usage, select on sequence myappdb.factura_detalles_id_seq to anon, authenticated, service_role;
grant usage, select on sequence myappdb.factura_numero_seq to anon, authenticated, service_role;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = 'facturas' and policyname = 'facturas_select_local_app') then
    create policy facturas_select_local_app on myappdb.facturas for select to anon, authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = 'facturas' and policyname = 'facturas_insert_local_app') then
    create policy facturas_insert_local_app on myappdb.facturas for insert to anon, authenticated with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = 'facturas' and policyname = 'facturas_update_local_app') then
    create policy facturas_update_local_app on myappdb.facturas for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = 'facturas' and policyname = 'facturas_delete_local_app') then
    create policy facturas_delete_local_app on myappdb.facturas for delete to anon, authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = 'factura_detalles' and policyname = 'factura_detalles_select_local_app') then
    create policy factura_detalles_select_local_app on myappdb.factura_detalles for select to anon, authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = 'factura_detalles' and policyname = 'factura_detalles_insert_local_app') then
    create policy factura_detalles_insert_local_app on myappdb.factura_detalles for insert to anon, authenticated with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = 'factura_detalles' and policyname = 'factura_detalles_update_local_app') then
    create policy factura_detalles_update_local_app on myappdb.factura_detalles for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = 'factura_detalles' and policyname = 'factura_detalles_delete_local_app') then
    create policy factura_detalles_delete_local_app on myappdb.factura_detalles for delete to anon, authenticated using (true);
  end if;
end;
$$;

commit;
