begin;

create schema if not exists myappdb;

create table if not exists myappdb.clients (
  id integer generated by default as identity primary key,
  codigo text not null,
  nombre_completo text not null,
  empresa text,
  tipo_documento text not null,
  numero_documento text not null,
  telefono text,
  correo text,
  direccion text,
  ciudad text,
  categoria text not null default 'Minorista',
  limite_credito numeric(14, 2) not null default 0,
  balance numeric(14, 2) not null default 0,
  estado text not null default 'Activo',
  ultima_compra text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint clients_codigo_key unique (codigo),
  constraint clients_numero_documento_key unique (numero_documento),
  constraint clients_tipo_documento_check check (tipo_documento in ('Cedula', 'RNC', 'Pasaporte')),
  constraint clients_categoria_check check (categoria in ('Minorista', 'Mayorista', 'Corporativo')),
  constraint clients_estado_check check (estado in ('Activo', 'Inactivo', 'Bloqueado'))
);

create index if not exists clients_nombre_completo_idx on myappdb.clients (nombre_completo);
create index if not exists clients_empresa_idx on myappdb.clients (empresa);
create index if not exists clients_estado_idx on myappdb.clients (estado);
create index if not exists clients_categoria_idx on myappdb.clients (categoria);

create or replace function myappdb.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'clients_set_updated_at'
      and tgrelid = 'myappdb.clients'::regclass
  ) then
    create trigger clients_set_updated_at
    before update on myappdb.clients
    for each row
    execute function myappdb.set_updated_at();
  end if;
end;
$$;

alter table myappdb.clients enable row level security;

grant usage on schema myappdb to anon, authenticated, service_role;
grant select, insert, update, delete on myappdb.clients to anon, authenticated, service_role;
grant usage, select on sequence myappdb.clients_id_seq to anon, authenticated, service_role;
grant execute on function myappdb.set_updated_at() to anon, authenticated, service_role;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'clients'
      and policyname = 'clients_select_local_app'
  ) then
    create policy "clients_select_local_app"
    on myappdb.clients
    for select
    to anon, authenticated
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'clients'
      and policyname = 'clients_insert_local_app'
  ) then
    create policy "clients_insert_local_app"
    on myappdb.clients
    for insert
    to anon, authenticated
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'clients'
      and policyname = 'clients_update_local_app'
  ) then
    create policy "clients_update_local_app"
    on myappdb.clients
    for update
    to anon, authenticated
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'clients'
      and policyname = 'clients_delete_local_app'
  ) then
    create policy "clients_delete_local_app"
    on myappdb.clients
    for delete
    to anon, authenticated
    using (true);
  end if;
end;
$$;

commit;
