begin;

create table if not exists myappdb.certificados_firma_digital (
  id bigint generated by default as identity primary key,
  empresa_id integer not null unique references myappdb.empresas(id),
  nombre_archivo text not null,
  tipo_archivo text not null,
  archivo bytea not null,
  titular text not null,
  emisor text not null,
  numero_serie text not null,
  valido_desde timestamptz not null,
  valido_hasta timestamptz not null,
  cargado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

alter table myappdb.certificados_firma_digital enable row level security;

create or replace function myappdb.guardar_certificado_firma_digital(
  p_nombre_archivo text,
  p_tipo_archivo text,
  p_archivo_base64 text,
  p_titular text,
  p_emisor text,
  p_numero_serie text,
  p_valido_desde timestamptz,
  p_valido_hasta timestamptz
)
returns table (
  nombre_archivo text,
  titular text,
  emisor text,
  numero_serie text,
  valido_desde timestamptz,
  valido_hasta timestamptz,
  cargado_en timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_empresa_id integer;
  v_archivo bytea;
begin
  select u.empresa_id into v_empresa_id
  from myappdb.usuarios as u
  where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo';

  if not found then
    raise exception 'No se encontró un usuario activo asociado a una empresa.' using errcode = '42501';
  end if;

  if nullif(trim(p_nombre_archivo), '') is null or nullif(trim(p_archivo_base64), '') is null then
    raise exception 'Debes indicar un certificado válido.' using errcode = '22023';
  end if;

  v_archivo := decode(p_archivo_base64, 'base64');
  if octet_length(v_archivo) > 5242880 then
    raise exception 'El certificado no puede superar 5 MB.' using errcode = '22023';
  end if;

  insert into myappdb.certificados_firma_digital (
    empresa_id, nombre_archivo, tipo_archivo, archivo, titular, emisor,
    numero_serie, valido_desde, valido_hasta
  ) values (
    v_empresa_id, trim(p_nombre_archivo), coalesce(nullif(trim(p_tipo_archivo), ''), 'application/x-pkcs12'),
    v_archivo, trim(p_titular), trim(p_emisor), trim(p_numero_serie), p_valido_desde, p_valido_hasta
  )
  on conflict (empresa_id) do update
  set nombre_archivo = excluded.nombre_archivo,
      tipo_archivo = excluded.tipo_archivo,
      archivo = excluded.archivo,
      titular = excluded.titular,
      emisor = excluded.emisor,
      numero_serie = excluded.numero_serie,
      valido_desde = excluded.valido_desde,
      valido_hasta = excluded.valido_hasta,
      cargado_en = now(),
      actualizado_en = now()
  returning certificados_firma_digital.nombre_archivo, certificados_firma_digital.titular,
    certificados_firma_digital.emisor, certificados_firma_digital.numero_serie,
    certificados_firma_digital.valido_desde, certificados_firma_digital.valido_hasta,
    certificados_firma_digital.cargado_en
  into nombre_archivo, titular, emisor, numero_serie, valido_desde, valido_hasta, cargado_en;

  return next;
end;
$$;

create or replace function myappdb.obtener_certificado_firma_digital()
returns table (
  nombre_archivo text,
  titular text,
  emisor text,
  numero_serie text,
  valido_desde timestamptz,
  valido_hasta timestamptz,
  cargado_en timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_empresa_id integer;
begin
  select u.empresa_id into v_empresa_id
  from myappdb.usuarios as u
  where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo';

  if not found then
    raise exception 'No se encontró un usuario activo asociado a una empresa.' using errcode = '42501';
  end if;

  return query
  select c.nombre_archivo, c.titular, c.emisor, c.numero_serie,
    c.valido_desde, c.valido_hasta, c.cargado_en
  from myappdb.certificados_firma_digital as c
  where c.empresa_id = v_empresa_id;
end;
$$;

revoke all on table myappdb.certificados_firma_digital from public, anon, authenticated;
revoke all on function myappdb.guardar_certificado_firma_digital(text, text, text, text, text, text, timestamptz, timestamptz) from public;
revoke all on function myappdb.obtener_certificado_firma_digital() from public;
grant execute on function myappdb.guardar_certificado_firma_digital(text, text, text, text, text, text, timestamptz, timestamptz) to authenticated;
grant execute on function myappdb.obtener_certificado_firma_digital() to authenticated;

commit;
