begin;

create table if not exists myappdb.cotizaciones (
  id bigint generated by default as identity primary key,
  idempres integer not null references myappdb.empresas(id) on delete restrict,
  idsucursal bigint not null references myappdb.sucursales(idsucursal) on delete restrict,
  numero_cotizacion text not null unique,
  fecha date not null default current_date,
  vigencia_hasta date,
  cliente_nombre text not null,
  cliente_rnc text,
  cliente_telefono text,
  cliente_correo text,
  cliente_direccion text,
  notas text,
  subtotal numeric(14,2) not null default 0,
  itbis numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  estado text not null default 'Activa' check (estado in ('Activa','Vencida','Cancelada')),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);
create table if not exists myappdb.cotizacion_detalles (
  id bigint generated by default as identity primary key,
  cotizacion_id bigint not null references myappdb.cotizaciones(id) on delete cascade,
  codigo_producto text,
  descripcion text not null,
  cantidad numeric(14,2) not null check (cantidad > 0),
  precio_unitario numeric(14,2) not null check (precio_unitario >= 0),
  tasa_itbis numeric(5,2) not null default 18 check (tasa_itbis between 0 and 100),
  total_linea numeric(14,2) not null check (total_linea >= 0)
);
create index if not exists cotizaciones_empresa_fecha_idx on myappdb.cotizaciones(idempres, idsucursal, fecha desc);
create index if not exists cotizacion_detalles_cotizacion_idx on myappdb.cotizacion_detalles(cotizacion_id);
alter table myappdb.cotizaciones enable row level security;
alter table myappdb.cotizacion_detalles enable row level security;
grant select, insert, update, delete on myappdb.cotizaciones, myappdb.cotizacion_detalles to authenticated, service_role;
grant usage, select on sequence myappdb.cotizaciones_id_seq, myappdb.cotizacion_detalles_id_seq to authenticated, service_role;
create policy cotizaciones_empresa on myappdb.cotizaciones for all to authenticated using (idempres=(select empresa_id from myappdb.usuarios where auth_usuario_id=(select auth.uid()) and estado='Activo')) with check (idempres=(select empresa_id from myappdb.usuarios where auth_usuario_id=(select auth.uid()) and estado='Activo'));
create policy cotizacion_detalles_empresa on myappdb.cotizacion_detalles for all to authenticated using (exists(select 1 from myappdb.cotizaciones c where c.id=cotizacion_id and c.idempres=(select empresa_id from myappdb.usuarios where auth_usuario_id=(select auth.uid()) and estado='Activo'))) with check (exists(select 1 from myappdb.cotizaciones c where c.id=cotizacion_id and c.idempres=(select empresa_id from myappdb.usuarios where auth_usuario_id=(select auth.uid()) and estado='Activo')));
create or replace function myappdb.crear_cotizacion(p_cotizacion jsonb, p_detalles jsonb) returns table(id bigint, numero_cotizacion text) language plpgsql security invoker set search_path='' as $$
declare v_empresa integer; v_sucursal bigint; v_contador integer; v_numero text; v_id bigint;
begin
  select empresa_id,sucursal_id into v_empresa,v_sucursal from myappdb.usuarios where auth_usuario_id=(select auth.uid()) and estado='Activo';
  if not found or v_sucursal is null then raise exception 'No se encontró un usuario activo con empresa y sucursal.'; end if;
  if jsonb_array_length(coalesce(p_detalles,'[]'::jsonb))=0 then raise exception 'La cotización debe tener al menos una línea.'; end if;
  insert into myappdb.contador_doc(id_empres,nom_empresa,ano,factura,cotizacion,nota_credito,gasto_menores,recibo,sucursal_id) select e.id,e.nombre_comercial,extract(year from current_date)::smallint,0,0,0,0,0,v_sucursal::smallint from myappdb.empresas e where e.id=v_empresa on conflict(id_empres,ano,sucursal_id) do nothing;
  update myappdb.contador_doc set cotizacion=cotizacion+1 where id_empres=v_empresa and sucursal_id=v_sucursal::smallint and ano=extract(year from current_date)::smallint returning cotizacion into v_contador;
  v_numero := 'COT-' || extract(year from current_date)::text || lpad(v_sucursal::text,2,'0') || lpad(v_contador::text,5,'0');
  insert into myappdb.cotizaciones(idempres,idsucursal,numero_cotizacion,fecha,vigencia_hasta,cliente_nombre,cliente_rnc,cliente_telefono,cliente_correo,cliente_direccion,notas,subtotal,itbis,total,estado) values(v_empresa,v_sucursal,v_numero,coalesce(nullif(p_cotizacion->>'fecha','')::date,current_date),nullif(p_cotizacion->>'vigenciaHasta','')::date,p_cotizacion->>'clienteNombre',nullif(p_cotizacion->>'clienteRnc',''),nullif(p_cotizacion->>'clienteTelefono',''),nullif(p_cotizacion->>'clienteCorreo',''),nullif(p_cotizacion->>'clienteDireccion',''),nullif(p_cotizacion->>'notas',''),coalesce((p_cotizacion->>'subtotal')::numeric,0),coalesce((p_cotizacion->>'itbis')::numeric,0),coalesce((p_cotizacion->>'total')::numeric,0),'Activa') returning cotizaciones.id into v_id;
  insert into myappdb.cotizacion_detalles(cotizacion_id,codigo_producto,descripcion,cantidad,precio_unitario,tasa_itbis,total_linea) select v_id,nullif(d->>'codigo',''),d->>'descripcion',(d->>'cantidad')::numeric,(d->>'precio')::numeric,coalesce((d->>'itbis')::numeric,0),(d->>'total')::numeric from jsonb_array_elements(p_detalles) d;
  return query select v_id,v_numero;
end; $$;
grant execute on function myappdb.crear_cotizacion(jsonb,jsonb) to authenticated,service_role;
commit;
