begin;

create schema if not exists myappdb;

create table if not exists myappdb.empresas (
  id integer generated by default as identity primary key,
  nombre_comercial text not null,
  razon_social text not null,
  rnc text not null,
  correo text not null,
  telefono text,
  ciudad text,
  sitio_web text,
  direccion text,
  categoria text not null default 'Principal',
  estado text not null default 'Activa',
  cantidad_sucursales integer not null default 1,
  ultima_actualizacion text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint empresas_rnc_key unique (rnc),
  constraint empresas_estado_check check (estado in ('Activa', 'Inactiva'))
);

create index if not exists empresas_nombre_comercial_idx on myappdb.empresas (nombre_comercial);
create index if not exists empresas_razon_social_idx on myappdb.empresas (razon_social);
create index if not exists empresas_estado_idx on myappdb.empresas (estado);
create index if not exists empresas_categoria_idx on myappdb.empresas (categoria);

create or replace function myappdb.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'empresas_set_updated_at'
      and tgrelid = 'myappdb.empresas'::regclass
  ) then
    create trigger empresas_set_updated_at
    before update on myappdb.empresas
    for each row
    execute function myappdb.set_updated_at();
  end if;
end;
$$;

alter table myappdb.empresas enable row level security;

grant usage on schema myappdb to anon, authenticated, service_role;
grant select, insert, update, delete on myappdb.empresas to anon, authenticated, service_role;
grant usage, select on sequence myappdb.empresas_id_seq to anon, authenticated, service_role;
grant execute on function myappdb.set_updated_at() to anon, authenticated, service_role;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'empresas'
      and policyname = 'empresas_select_local_app'
  ) then
    create policy "empresas_select_local_app"
    on myappdb.empresas
    for select
    to anon, authenticated
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'empresas'
      and policyname = 'empresas_insert_local_app'
  ) then
    create policy "empresas_insert_local_app"
    on myappdb.empresas
    for insert
    to anon, authenticated
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'empresas'
      and policyname = 'empresas_update_local_app'
  ) then
    create policy "empresas_update_local_app"
    on myappdb.empresas
    for update
    to anon, authenticated
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'empresas'
      and policyname = 'empresas_delete_local_app'
  ) then
    create policy "empresas_delete_local_app"
    on myappdb.empresas
    for delete
    to anon, authenticated
    using (true);
  end if;
end;
$$;

commit;
