begin;

create schema if not exists myappdb;

create table if not exists myappdb.usuarios (
  id integer generated by default as identity primary key,
  nombre text not null,
  apellido text not null,
  nombre_completo text not null,
  correo text not null,
  telefono text,
  empresa_id integer,
  sucursal text,
  rol text not null,
  estado text not null default 'Activo',
  avatar text,
  ultima_actualizacion text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint usuarios_correo_key unique (correo),
  constraint usuarios_estado_check check (estado in ('Activo', 'Inactivo'))
);

create table if not exists myappdb.rnc (
  id integer generated by default as identity primary key,
  rnc text not null,
  razon_social text not null,
  nombre_comercial text not null,
  categoria text not null default 'Contribuyente Normal',
  direccion text,
  telefono text,
  correo text,
  estado_dgii text not null default 'Activo',
  estado_sincronizacion text not null default 'Pendiente',
  ultima_consulta text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint rnc_rnc_key unique (rnc),
  constraint rnc_estado_dgii_check check (estado_dgii in ('Activo', 'Suspendido', 'Pendiente')),
  constraint rnc_estado_sincronizacion_check check (estado_sincronizacion in ('Sincronizado', 'Pendiente', 'Error'))
);

create table if not exists myappdb.ncf_empresas (
  id integer generated by default as identity primary key,
  rnc text not null,
  razon_social text not null,
  nombre_comercial text not null,
  direccion text,
  telefono text,
  correo text,
  estado text not null default 'Activa',
  fecha_registro text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint ncf_empresas_rnc_key unique (rnc),
  constraint ncf_empresas_estado_check check (estado in ('Activa', 'Inactiva'))
);

create table if not exists myappdb.ncf_secuencias (
  id integer generated by default as identity primary key,
  empresa_id integer not null,
  tipo_ncf text not null,
  serie text not null,
  rango_inicial text not null,
  rango_final text not null,
  fecha_autorizacion text not null,
  fecha_vencimiento text not null,
  usados integer not null default 0,
  total integer not null default 0,
  estado text not null default 'Activa',
  alerta boolean not null default false,
  porcentaje_alerta integer not null default 80,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint ncf_secuencias_estado_check check (estado in ('Activa', 'Agotada', 'Vencida')),
  constraint ncf_secuencias_alerta_check check (porcentaje_alerta between 0 and 100)
);

create index if not exists usuarios_nombre_completo_idx on myappdb.usuarios (nombre_completo);
create index if not exists usuarios_empresa_id_idx on myappdb.usuarios (empresa_id);
create index if not exists usuarios_estado_idx on myappdb.usuarios (estado);

create index if not exists rnc_razon_social_idx on myappdb.rnc (razon_social);
create index if not exists rnc_nombre_comercial_idx on myappdb.rnc (nombre_comercial);
create index if not exists rnc_estado_dgii_idx on myappdb.rnc (estado_dgii);

create index if not exists ncf_empresas_razon_social_idx on myappdb.ncf_empresas (razon_social);
create index if not exists ncf_empresas_nombre_comercial_idx on myappdb.ncf_empresas (nombre_comercial);
create index if not exists ncf_empresas_estado_idx on myappdb.ncf_empresas (estado);

create index if not exists ncf_secuencias_empresa_id_idx on myappdb.ncf_secuencias (empresa_id);
create index if not exists ncf_secuencias_tipo_ncf_idx on myappdb.ncf_secuencias (tipo_ncf);
create index if not exists ncf_secuencias_estado_idx on myappdb.ncf_secuencias (estado);

create or replace function myappdb.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

do $$
declare
  item record;
begin
  for item in
    select * from (values
      ('usuarios', 'usuarios_set_updated_at'),
      ('rnc', 'rnc_set_updated_at'),
      ('ncf_empresas', 'ncf_empresas_set_updated_at'),
      ('ncf_secuencias', 'ncf_secuencias_set_updated_at')
    ) as triggers(table_name, trigger_name)
  loop
    if not exists (
      select 1
      from pg_trigger
      where tgname = item.trigger_name
        and tgrelid = ('myappdb.' || item.table_name)::regclass
    ) then
      execute format(
        'create trigger %I before update on myappdb.%I for each row execute function myappdb.set_updated_at()',
        item.trigger_name,
        item.table_name
      );
    end if;
  end loop;
end;
$$;

alter table myappdb.usuarios enable row level security;
alter table myappdb.rnc enable row level security;
alter table myappdb.ncf_empresas enable row level security;
alter table myappdb.ncf_secuencias enable row level security;

grant usage on schema myappdb to anon, authenticated, service_role;
grant select, insert, update, delete on myappdb.usuarios to anon, authenticated, service_role;
grant select, insert, update, delete on myappdb.rnc to anon, authenticated, service_role;
grant select, insert, update, delete on myappdb.ncf_empresas to anon, authenticated, service_role;
grant select, insert, update, delete on myappdb.ncf_secuencias to anon, authenticated, service_role;
grant usage, select on sequence myappdb.usuarios_id_seq to anon, authenticated, service_role;
grant usage, select on sequence myappdb.rnc_id_seq to anon, authenticated, service_role;
grant usage, select on sequence myappdb.ncf_empresas_id_seq to anon, authenticated, service_role;
grant usage, select on sequence myappdb.ncf_secuencias_id_seq to anon, authenticated, service_role;
grant execute on function myappdb.set_updated_at() to anon, authenticated, service_role;

do $$
declare
  item record;
begin
  for item in
    select * from (values
      ('usuarios'),
      ('rnc'),
      ('ncf_empresas'),
      ('ncf_secuencias')
    ) as tables(table_name)
  loop
    if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = item.table_name and policyname = item.table_name || '_select_local_app') then
      execute format('create policy %I on myappdb.%I for select to anon, authenticated using (true)', item.table_name || '_select_local_app', item.table_name);
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = item.table_name and policyname = item.table_name || '_insert_local_app') then
      execute format('create policy %I on myappdb.%I for insert to anon, authenticated with check (true)', item.table_name || '_insert_local_app', item.table_name);
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = item.table_name and policyname = item.table_name || '_update_local_app') then
      execute format('create policy %I on myappdb.%I for update to anon, authenticated using (true) with check (true)', item.table_name || '_update_local_app', item.table_name);
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = item.table_name and policyname = item.table_name || '_delete_local_app') then
      execute format('create policy %I on myappdb.%I for delete to anon, authenticated using (true)', item.table_name || '_delete_local_app', item.table_name);
    end if;
  end loop;
end;
$$;

commit;
