-- Generated from myappdb.sql (MySQL) for Supabase/PostgreSQL
begin;

create table if not exists "CotizacionCounter" (
  "year" integer NOT NULL,
  "last_number" integer NOT NULL,
  PRIMARY KEY ("year")
);

create table if not exists "DetFactura" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "df_codFact" varchar(12) NOT NULL,
  "df_fecFact" date NULL,
  "df_codMerc" varchar(15) NOT NULL,
  "df_tipoMerc" varchar(1) NULL,
  "df_codGrupo" varchar(10) NULL,
  "df_desMerc" varchar(30) NULL,
  "df_canMerc" decimal(10, 2) NULL,
  "df_preMerc" decimal(10, 2) NULL,
  "df_valMerc" decimal(12, 2) NULL,
  "df_unidad" varchar(8) NULL,
  "df_cosMerc" decimal(10, 2) NULL,
  "df_codClie" decimal(5, 0) NULL,
  "df_imp" varchar(1) NULL,
  "df_status" varchar(3) NULL,
  "enviado" decimal(1, 0) NULL,
  "reimpresa" decimal(1, 0) NULL,
  "df_nomClie" varchar(10) NULL,
  "df_codEpr" varchar(6) NULL,
  "df_codSucu" varchar(10) NULL,
  "df_pendiente" char(1) NULL,
  "df_canpend" decimal(10, 2) NULL,
  PRIMARY KEY ("id")
);

create table if not exists "Usuario" (
  "codUsuario" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "idUsuario" varchar(10) NULL,
  "claveUsuario" varchar(255) NULL,
  "nombreUsuario" varchar(100) NULL,
  "nivel" integer NULL,
  "metaVenta" decimal(5, 2) NULL,
  "correo" varchar(40) NULL,
  "claveCorreo" varchar(15) NULL,
  "sucursalid" integer NULL,
  "idtipoUsuario" integer NULL,
  "idpermiso" integer NULL,
  "cod_empre" varchar(30) NULL,
  PRIMARY KEY ("codUsuario")
);

create table if not exists "choferes" (
  "id" integer NOT NULL,
  "codChofer" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nomChofer" varchar(30) NULL,
  "cedChofer" char(11) NULL,
  "statusChofer" boolean NULL,
  PRIMARY KEY ("codChofer", "id")
);

create table if not exists "cierrecaja" (
  "idcierre" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "feccierre" date NULL,
  "tefectivo" decimal(12, 2) NULL,
  "ttarjeta" decimal(12, 2) NULL,
  "tdeposito" decimal(12, 2) NULL,
  "totalcierre" decimal(12, 2) NULL,
  "tcheque" decimal(12, 2) NULL,
  "factini" varchar(255) NULL,
  "factfin" varchar(255) NULL,
  "cajera" varchar(255) NULL,
  "nota" varchar(255) NULL,
  PRIMARY KEY ("idcierre")
);

create table if not exists "clientes" (
  "cl_codClie" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "cl_nomClie" varchar(35) NOT NULL,
  "cl_dirClie" varchar(40) NOT NULL,
  "cl_codSect" integer NULL,
  "cl_codZona" integer NULL,
  "cl_telClie" varchar(20) NULL,
  "cl_tipo" varchar(50) NULL,
  "cl_status" boolean NULL,
  "cl_rnc" integer NULL,
  "cl_codsucursal" varchar(10) NULL,
  PRIMARY KEY ("cl_codClie")
);

create table if not exists "contfactura" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "idsucursal" integer NULL,
  "ano" integer NULL,
  "contador" integer NULL,
  "contsalida" integer NULL,
  "contentrada" integer NULL,
  "contvinterna" integer NULL,
  PRIMARY KEY ("id")
);

create table if not exists "cotizacion" (
  "ct_codcoti" char(10) NOT NULL,
  "ct_feccoti" date NULL,
  "ct_valcoti" decimal(9, 2) NULL,
  "ct_itbis" decimal(9, 2) NULL,
  "ct_codclie" integer NULL,
  "ct_nomclie" varchar(50) NULL,
  "ct_rnc" char(11) NULL,
  "ct_telclie" char(17) NULL,
  "ct_dirclie" char(50) NULL,
  "ct_correo" char(50) NULL,
  "ct_codvend" char(5) NULL,
  "ct_nomvend" char(15) NULL,
  "ct_nota" text NULL,
  "ct_status" char(4) NULL,
  "ct_codEmpr" varchar(6) NULL,
  "ct_cod_sucu" integer NULL,
  PRIMARY KEY ("ct_codcoti")
);

create table if not exists "ctr_factura" (
  "year" decimal(10, 0) NOT NULL,
  "last_number" decimal(10, 0) NULL,
  "control" decimal(10, 0) NULL,
  "ncfvalorf" varchar(255) NULL,
  "fecvalorf" date NULL,
  "cantncfvalorf" decimal(10, 0) NULL,
  "ctrvalorf" decimal(10, 0) NULL,
  "ncfconsumo" varchar(255) NULL,
  "cantconsumo" decimal(10, 0) NULL,
  "ctrconsumo" decimal(10, 0) NULL,
  "ncfespecial" varchar(255) NULL,
  "fecespecial" date NULL,
  "cantespecial" decimal(10, 0) NULL,
  "ctrespecial" decimal(10, 0) NULL,
  "ncfguberna" varchar(255) NULL,
  "fecguberna" date NULL,
  "cantguberna" decimal(10, 0) NULL,
  "ctrguberna" decimal(10, 0) NULL,
  "ctr_ini" decimal(10, 0) NULL,
  "ctr_fin" decimal(10, 0) NULL,
  "ctr_f" decimal(10, 0) NULL,
  "ctr_t" decimal(10, 0) NULL,
  PRIMARY KEY ("year")
);

create table if not exists "despachadores" (
  "CodDesp" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nomDesp" varchar(30) NOT NULL,
  "tipoDesp" char(2) NOT NULL,
  "statusDespachadores" boolean NULL,
  "cedDesp" varchar(11) NOT NULL,
  PRIMARY KEY ("CodDesp")
);

create table if not exists "detcotizacion" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "dc_codcoti" varchar(10) NOT NULL,
  "dc_codmerc" varchar(15) NOT NULL,
  "dc_descrip" varchar(40) NULL,
  "dc_canmerc" decimal(10, 2) NULL,
  "dc_premerc" decimal(9, 2) NULL,
  "dc_valmerc" decimal(10, 2) NULL,
  "dc_unidad" varchar(10) NULL,
  "dc_costmer" decimal(10, 2) NULL,
  "dc_codclie" integer NULL,
  "dc_item" integer NULL,
  "dc_status" varchar(4) NULL,
  "dc_codEmpr" varchar(6) NULL,
  "dc_codSucu" integer NULL,
  PRIMARY KEY ("id")
);

create table if not exists "detentradamerc" (
  "de_codEntr" varchar(12) NOT NULL,
  "de_codMerc" varchar(15) NOT NULL,
  "de_desMerc" varchar(30) NULL,
  "de_canEntr" decimal(8, 2) NULL,
  "de_preMerc" decimal(9, 2) NULL,
  "de_valEntr" decimal(10, 2) NULL,
  "de_unidad" varchar(10) NULL,
  "de_cosMerc" decimal(10, 2) NULL,
  "de_codSupl" decimal(7, 0) NULL,
  "de_fecEntr" date NULL,
  "de_codEmpr" varchar(6) NULL,
  "de_codSucu" integer NULL,
  "de_tipo" varchar(10) NULL,
  PRIMARY KEY ("de_codEntr", "de_codMerc")
);

create table if not exists "detsalida" (
  "idsalida" integer NOT NULL,
  "idsucursal" integer NULL,
  "codSalida" varchar(255) NOT NULL,
  "codFact" varchar(255) NOT NULL,
  "fecFact" date NULL,
  "nomClie" varchar(255) NULL,
  "valFact" decimal(10, 2) NULL,
  "codChofer" decimal(10, 0) NULL,
  "nomChofer" varchar(255) NULL,
  "valAbono" decimal(10, 2) NULL,
  "devolucion" char(1) NULL,
  "valDevolucion" decimal(10, 2) NULL,
  "entregada" char(1) NULL,
  "pagado" char(1) NULL,
  "status" char(1) NULL,
  "imp" char(1) NULL,
  PRIMARY KEY ("codSalida", "codFact")
);

create table if not exists "detventainterna" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "df_codFact" varchar(12) NOT NULL,
  "df_fecFact" date NULL,
  "df_codMerc" varchar(15) NOT NULL,
  "df_tipoMerc" varchar(1) NULL,
  "df_codGrupo" varchar(10) NULL,
  "df_desMerc" varchar(30) NULL,
  "df_canMerc" decimal(10, 2) NOT NULL,
  "df_preMerc" decimal(10, 2) NOT NULL,
  "df_valMerc" decimal(12, 2) NULL,
  "df_unidad" varchar(8) NULL,
  "df_cosMerc" decimal(10, 2) NULL,
  "df_codClie" decimal(5, 0) NULL,
  "df_status" varchar(3) NULL,
  "df_nomClie" varchar(10) NULL,
  "df_codEmpr" varchar(6) NULL,
  "df_codSucu" integer NULL,
  "df_tipo" varchar(10) NULL,
  PRIMARY KEY ("id")
);

create table if not exists "devolucion" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "fecha" timestamp NULL,
  "codentrada" varchar(255) NULL,
  "codsalida" varchar(255) NULL,
  PRIMARY KEY ("id")
);

create table if not exists "dtipousuario" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "idtipousuario" integer NULL,
  "idmodulo" integer NULL,
  "lectura" varchar(1) NULL,
  "acceso" varchar(1) NULL,
  PRIMARY KEY ("id")
);

create table if not exists "empresas" (
  "cod_empre" varchar(255) NOT NULL,
  "nom_empre" varchar(255) NOT NULL,
  "dir_empre" varchar(255) NOT NULL,
  "tel_empre" varchar(255) NOT NULL,
  "rnc_empre" varchar(13) NOT NULL,
  "letra_empre" varchar(3) NULL,
  PRIMARY KEY ("cod_empre")
);

create table if not exists "encf" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "cantencf" decimal(10, 0) NULL,
  "countencf" decimal(10, 0) NULL,
  "alertaencf" decimal(10, 0) NULL,
  "codempr" varchar(6) NULL,
  "desdeencf" decimal(10, 0) NULL,
  "fechaencf" date NULL,
  "hastaencf" decimal(10, 0) NULL,
  "tipoencf" varchar(4) NULL,
  "tipo" integer NULL,
  PRIMARY KEY ("id")
);

create table if not exists "entradamerc" (
  "me_codEntr" varchar(255) NOT NULL,
  "me_fecEntr" date NULL,
  "me_valEntr" decimal(10, 2) NULL,
  "me_codSupl" varchar(6) NULL,
  "me_nomSupl" varchar(255) NULL,
  "me_facSupl" varchar(30) NULL,
  "me_fecSupl" date NULL,
  "me_status" varchar(4) NULL,
  "me_codVend" varchar(5) NULL,
  "me_nomVend" varchar(15) NULL,
  "imgfactura" text NULL,
  "nota" text NULL,
  "vendedor" varchar(25) NULL,
  "despachado" varchar(25) NULL,
  "chofer" varchar(25) NULL,
  "me_rncSupl" integer NULL,
  "me_codEmpr" varchar(6) NULL,
  "me_codSucu" integer NULL,
  "me_tipo" varchar(10) NULL,
  PRIMARY KEY ("me_codEntr")
);

create table if not exists "entradamercCounter" (
  "year" integer NOT NULL,
  "last_number" integer NOT NULL,
  PRIMARY KEY ("year")
);

create table if not exists "factura" (
  "fa_codFact" varchar(12) NOT NULL,
  "fa_ncfFact" varchar(19) NULL,
  "fa_rncFact" varchar(13) NULL,
  "fa_fecNcf" date NULL,
  "fa_tipoNcf" integer NULL,
  "fa_fecFact" date NULL,
  "fa_fecHora" timestamp NULL,
  "fa_valFact" decimal(12, 2) NULL,
  "fa_itbiFact" decimal(12, 2) NULL,
  "fa_subFact" decimal(12, 2) NULL,
  "fa_desFact" decimal(10, 2) NULL,
  "fa_cosFact" decimal(12, 2) NULL,
  "fa_aboFact" decimal(12, 2) NULL,
  "fa_expFact" date NULL,
  "fa_codClie" integer NULL,
  "fa_nomClie" varchar(39) NULL,
  "fa_telClie" varchar(26) NULL,
  "fa_dirClie" varchar(40) NULL,
  "fa_contacto" varchar(30) NULL,
  "fa_codZona" integer NULL,
  "fa_desZona" varchar(25) NULL,
  "fa_codSect" integer NULL,
  "fa_sector" varchar(35) NULL,
  "fa_codVend" varchar(10) NULL,
  "fa_nomVend" varchar(15) NULL,
  "fa_notaFact" text NULL,
  "fa_usuario" varchar(30) NULL,
  "fa_envio" integer NULL,
  "fa_fpago" varchar(20) NULL,
  "fa_codfpago" integer NULL,
  "fa_status" varchar(3) NULL,
  "fa_tipoFact" integer NULL,
  "fa_imp" varchar(1) NULL,
  "fa_tipoRnc" integer NULL,
  "fa_fecha" varchar(8) NULL,
  "fa_codSucu" integer NULL,
  "fa_fehora" timestamp NULL,
  "fa_correo" varchar(30) NULL,
  "fa_codEmpr" varchar(6) NULL,
  "fa_impresa" char(1) NULL,
  "fa_reimpresa" char(1) NULL,
  "fa_entrega" char(1) NULL,
  "fa_impalmaf" char(1) NULL,
  "fa_impalmap" char(1) NULL,
  "fa_facturada" char(1) NULL,
  "fa_pendiente" char(1) NULL,
  "fa_despacho" char(1) NULL,
  "estado_dgii" varchar(255) NULL,
  "codseguridad" varchar(255) NULL,
  "qr_link" varchar(255) NULL,
  "fec_firma" varchar(255) NULL,
  "ECF" longtext NULL,
  "RFCE" longtext NULL,
  "estado_envio_dgii" varchar(50) NULL,
  "fa_cierre" char(1) NULL,
  "fa_salida" char(1) NULL,
  "idsalida" varchar(255) NULL,
  PRIMARY KEY ("fa_codFact")
);

create table if not exists "fentrega" (
  "idfentrega" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "desentrega" varchar(20) NOT NULL,
  PRIMARY KEY ("idfentrega")
);

create table if not exists "fpago" (
  "fp_codfpago" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "fp_descfpago" varchar(30) NOT NULL,
  PRIMARY KEY ("fp_codfpago")
);

create table if not exists "grupomerc" (
  "Codgrupo" varchar(3) NOT NULL,
  "Descgrupo" varchar(50) NOT NULL,
  "Tipomerc" char(1) NOT NULL,
  PRIMARY KEY ("Codgrupo")
);

create table if not exists "inventario" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "inv_codsucu" integer NOT NULL,
  "inv_codprod" varchar(20) NOT NULL,
  "inv_desprod" varchar(40) NULL,
  "inv_cosprod" decimal(12, 2) NULL,
  "inv_preprod" decimal(12, 2) NULL,
  "inv_existencia" decimal(10, 2) NULL,
  "inv_fechamov" timestamp NULL,
  PRIMARY KEY ("id", "inv_codsucu", "inv_codprod")
);

create table if not exists "modulo" (
  "idmodulo" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "descmodulo" varchar(30) NULL,
  "scceso" varchar(1) NULL,
  "lectura" varchar(1) NULL,
  PRIMARY KEY ("idmodulo")
);

create table if not exists "permiso" (
  "idpermiso" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "codusuario" integer NULL,
  "idmodulo" integer NULL,
  "acceso" varchar(1) NULL,
  "lectura" varchar(1) NULL,
  PRIMARY KEY ("idpermiso")
);

create table if not exists "productos2" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "in_codmerc" varchar(15) NULL,
  "in_categor" varchar(4) NULL,
  "in_tramo" varchar(8) NULL,
  "in_desmerc" varchar(30) NULL,
  "in_canmerc" double precision NULL,
  "in_caninve" double precision NULL,
  "in_fecinve" date NULL,
  "in_eximini" double precision NULL,
  "in_minvent" double precision NULL,
  "in_costmer" double precision NULL,
  "in_precmin" double precision NULL,
  "in_premerc" double precision NULL,
  "in_costpro" double precision NULL,
  "in_ucosto" double precision NULL,
  "in_porgana" double precision NULL,
  "in_peso" double precision NULL,
  "media" varchar(1) NULL,
  "in_longitu" double precision NULL,
  "in_unidad" varchar(8) NULL,
  "in_fecmodi" date NULL,
  "in_almacen" varchar(10) NULL,
  "imagen" text NULL,
  "in_exento" tinyint(1) NULL,
  "contror" tinyint(1) NULL,
  "atualisar" tinyint(1) NULL,
  "suma" double precision NULL,
  "existencia" double precision NULL,
  "salida" double precision NULL,
  "status" varchar(1) NULL,
  PRIMARY KEY ("id")
);

create table if not exists "recibo" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "fecha" timestamp NULL,
  "cantidad" decimal(12, 2) NULL,
  "nombre" varchar(255) NULL,
  "concepto" varchar(255) NULL,
  "fpago" integer NULL,
  PRIMARY KEY ("id")
);

create table if not exists "rnc" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "rnc" varchar(255) NOT NULL,
  "rason" varchar(255) NULL,
  "status" varchar(255) NULL,
  PRIMARY KEY ("id")
);

create table if not exists "salida" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "idsucursal" integer NULL,
  "codSalida" varchar(255) NULL,
  "fecSalida" date NULL,
  "horaSalida" timestamp NULL,
  "canFact" integer NULL,
  "valFact" decimal(10, 2) NULL,
  "valPagado" decimal(10, 2) NULL,
  "valDevolucion" decimal(10, 2) NULL,
  "codChofer" integer NULL,
  "nomChofer" varchar(255) NULL,
  "cedChofer" varchar(255) NULL,
  "status" varchar(255) NULL,
  "envia" varchar(255) NULL,
  "idusuario" integer NULL,
  PRIMARY KEY ("id")
);

create table if not exists "sector" (
  "se_codSect" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "se_desSect" varchar(30) NOT NULL,
  "se_codZona" integer NULL,
  "idsucursal" integer NULL,
  PRIMARY KEY ("se_codSect")
);

create table if not exists "sucursales" (
  "cod_sucursal" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nom_sucursal" varchar(255) NOT NULL,
  "Zona" varchar(255) NULL,
  "cod_empre" varchar(255) NOT NULL,
  "dir_sucursal" varchar(255) NULL,
  "tel_sucursal" varchar(255) NULL,
  PRIMARY KEY ("cod_sucursal")
);

create table if not exists "suplidor" (
  "su_codSupl" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "su_nomSupl" varchar(35) NOT NULL,
  "su_rncSupl" varchar(15) NULL,
  "su_dirSupl" varchar(50) NULL,
  "su_telSupl" varchar(26) NULL,
  "su_contact" varchar(30) NULL,
  "su_status" boolean NULL DEFAULT true,
  PRIMARY KEY ("su_codSupl")
);

create table if not exists "tiponcf" (
  "idNcf" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "desNcf" varchar(40) NOT NULL,
  "tipo" varchar(4) NOT NULL,
  "codigo" varchar(4) NULL,
  PRIMARY KEY ("idNcf")
);

create table if not exists "tipousuario" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "descripcion" varchar(30) NULL,
  PRIMARY KEY ("id")
);

create table if not exists "ventainterna" (
  "fa_codFact" varchar(12) NOT NULL,
  "fa_fecFact" date NULL,
  "fa_valFact" decimal(12, 2) NULL,
  "fa_itbiFact" decimal(12, 2) NULL,
  "fa_subFact" decimal(12, 2) NULL,
  "fa_cosFact" decimal(12, 2) NULL,
  "fa_codClie" integer NULL,
  "fa_nomClie" varchar(39) NULL,
  "fa_telClie" varchar(12) NULL,
  "fa_dirClie" varchar(40) NULL,
  "fa_codVend" varchar(10) NULL,
  "fa_nomVend" varchar(15) NULL,
  "fa_usuario" varchar(30) NULL,
  "fa_status" varchar(4) NULL,
  "fa_solicitud" varchar(12) NULL,
  "fa_codEmpr" varchar(6) NULL,
  "fa_codSucu" integer NULL,
  "fa_tipo" varchar(10) NULL,
  PRIMARY KEY ("fa_codFact")
);

create table if not exists "ventainternaCounter" (
  "year" integer NOT NULL,
  "last_number" integer NOT NULL,
  PRIMARY KEY ("year")
);

create table if not exists "zona" (
  "zo_codZona" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "zo_descrip" varchar(30) NOT NULL,
  PRIMARY KEY ("zo_codZona")
);



alter table "DetFactura" add CONSTRAINT "DetFactura_ibfk_1" FOREIGN KEY ("df_codFact") REFERENCES "factura" ("fa_codFact") ON DELETE RESTRICT ON UPDATE RESTRICT;
alter table "Usuario" add CONSTRAINT "Usuario_cod_empre_fkey" FOREIGN KEY ("cod_empre") REFERENCES "empresas" ("cod_empre") ON DELETE SET NULL ON UPDATE CASCADE;
alter table "Usuario" add CONSTRAINT "Usuario_idtipoUsuario_fkey" FOREIGN KEY ("idtipoUsuario") REFERENCES "tipousuario" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
alter table "Usuario" add CONSTRAINT "Usuario_sucursalid_fkey" FOREIGN KEY ("sucursalid") REFERENCES "sucursales" ("cod_sucursal") ON DELETE SET NULL ON UPDATE CASCADE;
alter table "clientes" add CONSTRAINT "fk_clientes_sector" FOREIGN KEY ("cl_codSect") REFERENCES "sector" ("se_codSect") ON DELETE RESTRICT ON UPDATE RESTRICT;
alter table "clientes" add CONSTRAINT "fk_clientes_zona" FOREIGN KEY ("cl_codZona") REFERENCES "zona" ("zo_codZona") ON DELETE RESTRICT ON UPDATE RESTRICT;
alter table "contfactura" add CONSTRAINT "contfactura_idsucursal_fkey" FOREIGN KEY ("idsucursal") REFERENCES "sucursales" ("cod_sucursal") ON DELETE SET NULL ON UPDATE CASCADE;
alter table "detcotizacion" add CONSTRAINT "detcotizacion_ibfk_1" FOREIGN KEY ("dc_codcoti") REFERENCES "cotizacion" ("ct_codcoti") ON DELETE RESTRICT ON UPDATE RESTRICT;
alter table "detentradamerc" add CONSTRAINT "detentradamerc_ibfk_1" FOREIGN KEY ("de_codEntr") REFERENCES "entradamerc" ("me_codEntr") ON DELETE RESTRICT ON UPDATE RESTRICT;
alter table "dtipousuario" add CONSTRAINT "dtipousuario_idmodulo_fkey" FOREIGN KEY ("idmodulo") REFERENCES "modulo" ("idmodulo") ON DELETE SET NULL ON UPDATE CASCADE;
alter table "dtipousuario" add CONSTRAINT "dtipousuario_idtipousuario_fkey" FOREIGN KEY ("idtipousuario") REFERENCES "tipousuario" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
alter table "encf" add CONSTRAINT "encf_codempr_fkey" FOREIGN KEY ("codempr") REFERENCES "empresas" ("cod_empre") ON DELETE SET NULL ON UPDATE CASCADE;
alter table "factura" add CONSTRAINT "factura_fa_codfpago_fkey" FOREIGN KEY ("fa_codfpago") REFERENCES "fpago" ("fp_codfpago") ON DELETE SET NULL ON UPDATE CASCADE;
alter table "factura" add CONSTRAINT "factura_fa_envio_fkey" FOREIGN KEY ("fa_envio") REFERENCES "fentrega" ("idfentrega") ON DELETE SET NULL ON UPDATE CASCADE;
alter table "permiso" add CONSTRAINT "permiso_codusuario_fkey" FOREIGN KEY ("codusuario") REFERENCES "Usuario" ("codUsuario") ON DELETE SET NULL ON UPDATE CASCADE;
alter table "permiso" add CONSTRAINT "permiso_idmodulo_fkey" FOREIGN KEY ("idmodulo") REFERENCES "modulo" ("idmodulo") ON DELETE SET NULL ON UPDATE CASCADE;
alter table "sector" add CONSTRAINT "sector_ibfk_1" FOREIGN KEY ("se_codZona") REFERENCES "zona" ("zo_codZona") ON DELETE RESTRICT ON UPDATE RESTRICT;
alter table "sector" add CONSTRAINT "sector_idsucursal_fkey" FOREIGN KEY ("idsucursal") REFERENCES "sucursales" ("cod_sucursal") ON DELETE SET NULL ON UPDATE CASCADE;
alter table "sucursales" add CONSTRAINT "sucursales_cod_empre_fkey" FOREIGN KEY ("cod_empre") REFERENCES "empresas" ("cod_empre") ON DELETE RESTRICT ON UPDATE CASCADE;

commit;
