begin;

create schema if not exists myappdb;

create table if not exists myappdb.tipos_ncf (
  id integer generated by default as identity primary key,
  codigo text not null,
  serie text not null,
  nombre text not null,
  descripcion text,
  tasa_itbis numeric(5, 2) not null default 0,
  es_electronico boolean not null default true,
  estado text not null default 'Activa',
  fecha_registro text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint tipos_ncf_codigo_key unique (codigo),
  constraint tipos_ncf_serie_key unique (serie),
  constraint tipos_ncf_estado_check check (estado in ('Activa', 'Inactiva')),
  constraint tipos_ncf_tasa_itbis_check check (tasa_itbis >= 0 and tasa_itbis <= 100)
);

create index if not exists tipos_ncf_codigo_idx on myappdb.tipos_ncf (codigo);
create index if not exists tipos_ncf_serie_idx on myappdb.tipos_ncf (serie);
create index if not exists tipos_ncf_estado_idx on myappdb.tipos_ncf (estado);

create or replace function myappdb.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'tipos_ncf_set_updated_at'
      and tgrelid = 'myappdb.tipos_ncf'::regclass
  ) then
    create trigger tipos_ncf_set_updated_at
    before update on myappdb.tipos_ncf
    for each row
    execute function myappdb.set_updated_at();
  end if;
end;
$$;

insert into myappdb.tipos_ncf
  (codigo, serie, nombre, descripcion, tasa_itbis, es_electronico, estado, fecha_registro)
values
  ('31', 'E31', 'Factura de Credito Fiscal Electronica', 'Comprobante electronico para operaciones gravadas con derecho a credito ITBIS.', 18, true, 'Activa', '28/08/2026'),
  ('32', 'E32', 'Factura de Consumo Electronica', 'Comprobante electronico para consumidores finales.', 18, true, 'Activa', '28/08/2026'),
  ('33', 'E33', 'Nota de Debito Electronica', 'Documento electronico para recuperar costos o gastos posteriores a una factura.', 18, true, 'Activa', '28/08/2026'),
  ('34', 'E34', 'Nota de Credito Electronica', 'Documento electronico para anular, devolver, descontar o corregir una factura.', 18, true, 'Activa', '28/08/2026'),
  ('41', 'E41', 'Comprobante Electronico de Compras', 'Comprobante emitido por compras a personas no registradas como contribuyentes.', 18, true, 'Activa', '28/08/2026'),
  ('43', 'E43', 'Comprobante Electronico para Gastos Menores', 'Comprobante para sustentar gastos menores relacionados al trabajo.', 18, true, 'Activa', '28/08/2026'),
  ('44', 'E44', 'Comprobante Electronico para Regimenes Especiales', 'Comprobante para transferencias o servicios exentos bajo regimenes especiales.', 0, true, 'Activa', '28/08/2026'),
  ('45', 'E45', 'Comprobante Electronico Gubernamental', 'Comprobante emitido a instituciones gubernamentales.', 18, true, 'Activa', '28/08/2026'),
  ('46', 'E46', 'Comprobante Electronico para Exportaciones', 'Comprobante para operaciones de exportacion de bienes y servicios.', 0, true, 'Activa', '28/08/2026'),
  ('47', 'E47', 'Comprobante Electronico para Pagos al Exterior', 'Comprobante para sustentar pagos realizados al exterior.', 0, true, 'Activa', '28/08/2026')
on conflict (codigo) do nothing;

alter table myappdb.tipos_ncf enable row level security;

grant usage on schema myappdb to anon, authenticated, service_role;
grant select, insert, update, delete on myappdb.tipos_ncf to anon, authenticated, service_role;
grant usage, select on sequence myappdb.tipos_ncf_id_seq to anon, authenticated, service_role;
grant execute on function myappdb.set_updated_at() to anon, authenticated, service_role;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = 'tipos_ncf' and policyname = 'tipos_ncf_select_local_app') then
    create policy tipos_ncf_select_local_app on myappdb.tipos_ncf for select to anon, authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = 'tipos_ncf' and policyname = 'tipos_ncf_insert_local_app') then
    create policy tipos_ncf_insert_local_app on myappdb.tipos_ncf for insert to anon, authenticated with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = 'tipos_ncf' and policyname = 'tipos_ncf_update_local_app') then
    create policy tipos_ncf_update_local_app on myappdb.tipos_ncf for update to anon, authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'myappdb' and tablename = 'tipos_ncf' and policyname = 'tipos_ncf_delete_local_app') then
    create policy tipos_ncf_delete_local_app on myappdb.tipos_ncf for delete to anon, authenticated using (true);
  end if;
end;
$$;

commit;
