begin;

create table if not exists myappdb.categorias_gastos (
  id bigint generated by default as identity primary key,
  descripcion text not null unique,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists myappdb.gastos_menores (
  id bigint generated by default as identity primary key,
  idempres integer not null references myappdb.empresas(id) on delete restrict,
  idsucursal integer not null,
  numero_control text not null unique,
  fecha date not null default current_date,
  categoria_id bigint not null references myappdb.categorias_gastos(id) on delete restrict,
  beneficiario text not null,
  rnc_cedula text,
  ncf_suplidor text,
  documento_referencia text,
  centro_costo text,
  responsable text,
  monto_gravado numeric(14, 2) not null default 0,
  monto_exento numeric(14, 2) not null default 0,
  tasa_itbis numeric(5, 2) not null default 18,
  monto_itbis numeric(14, 2) not null default 0,
  total numeric(14, 2) not null default 0,
  forma_pago text not null default 'Efectivo',
  concepto text not null,
  notas text,
  estado_dgii text not null default 'Borrador',
  dgii_track_id text,
  dgii_codigo_seguridad text,
  encf text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint gastos_menores_montos_check check (
    monto_gravado >= 0 and monto_exento >= 0 and monto_itbis >= 0 and total >= 0
  ),
  constraint gastos_menores_itbis_check check (tasa_itbis between 0 and 100),
  constraint gastos_menores_estado_check check (
    estado_dgii in ('Borrador', 'Enviado', 'Aceptado', 'Rechazado', 'Error')
  )
);

insert into myappdb.categorias_gastos (descripcion) values
  ('Alimentos y bebidas'),
  ('Combustible'),
  ('Comunicaciones'),
  ('Hospedaje'),
  ('Impuestos y tasas'),
  ('Mantenimiento'),
  ('Oficina y suministros'),
  ('Otros gastos'),
  ('Peajes y parqueos'),
  ('Publicidad'),
  ('Servicios profesionales'),
  ('Transporte'),
  ('Viáticos')
on conflict (descripcion) do nothing;

create index if not exists gastos_menores_empresa_fecha_idx
  on myappdb.gastos_menores (idempres, idsucursal, fecha desc);
create index if not exists gastos_menores_categoria_idx
  on myappdb.gastos_menores (categoria_id);

create trigger categorias_gastos_set_updated_at
before update on myappdb.categorias_gastos
for each row execute function myappdb.set_updated_at();

create trigger gastos_menores_set_updated_at
before update on myappdb.gastos_menores
for each row execute function myappdb.set_updated_at();

alter table myappdb.categorias_gastos enable row level security;
alter table myappdb.gastos_menores enable row level security;

grant select on myappdb.categorias_gastos to authenticated, service_role;
grant select, insert, update, delete on myappdb.gastos_menores to authenticated, service_role;
grant usage, select on sequence myappdb.categorias_gastos_id_seq to service_role;
grant usage, select on sequence myappdb.gastos_menores_id_seq to authenticated, service_role;

create policy categorias_gastos_select_authenticated
on myappdb.categorias_gastos for select to authenticated
using (true);

create policy gastos_menores_select_empresa
on myappdb.gastos_menores for select to authenticated
using (
  idempres = (
    select u.empresa_id from myappdb.usuarios u
    where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'
  )
);

create policy gastos_menores_insert_empresa
on myappdb.gastos_menores for insert to authenticated
with check (
  idempres = (
    select u.empresa_id from myappdb.usuarios u
    where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'
  )
);

create policy gastos_menores_update_empresa
on myappdb.gastos_menores for update to authenticated
using (
  idempres = (
    select u.empresa_id from myappdb.usuarios u
    where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'
  )
)
with check (
  idempres = (
    select u.empresa_id from myappdb.usuarios u
    where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'
  )
);

create policy gastos_menores_delete_empresa
on myappdb.gastos_menores for delete to authenticated
using (
  idempres = (
    select u.empresa_id from myappdb.usuarios u
    where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'
  )
);

create or replace function myappdb.crear_gasto_menor(p_gasto jsonb)
returns table (id bigint, numero_control text)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_empresa_id integer;
  v_sucursal_id integer;
  v_categoria_id bigint;
  v_id bigint;
  v_numero_control text;
begin
  select u.empresa_id, u.sucursal_id
  into v_empresa_id, v_sucursal_id
  from myappdb.usuarios u
  where u.auth_usuario_id = auth.uid() and u.estado = 'Activo';

  if v_empresa_id is null or v_sucursal_id is null then
    raise exception 'El usuario no tiene empresa o sucursal activa.' using errcode = '22023';
  end if;

  select c.id into v_categoria_id
  from myappdb.categorias_gastos c
  where lower(c.descripcion) = lower(trim(coalesce(p_gasto ->> 'categoria', '')))
    and c.activo = true;

  if v_categoria_id is null then
    raise exception 'La categoría de gasto seleccionada no existe o está inactiva.' using errcode = '22023';
  end if;

  insert into myappdb.gastos_menores (
    idempres, idsucursal, numero_control, fecha, categoria_id, beneficiario,
    rnc_cedula, ncf_suplidor, documento_referencia, centro_costo, responsable,
    monto_gravado, monto_exento, tasa_itbis, monto_itbis, total, forma_pago,
    concepto, notas, estado_dgii
  ) values (
    v_empresa_id, v_sucursal_id, '', coalesce(nullif(p_gasto ->> 'fecha', '')::date, current_date), v_categoria_id,
    trim(coalesce(p_gasto ->> 'beneficiario', '')),
    nullif(trim(coalesce(p_gasto ->> 'rncCedula', '')), ''),
    nullif(trim(coalesce(p_gasto ->> 'ncfSuplidor', '')), ''),
    nullif(trim(coalesce(p_gasto ->> 'documentoReferencia', '')), ''),
    nullif(trim(coalesce(p_gasto ->> 'centroCosto', '')), ''),
    nullif(trim(coalesce(p_gasto ->> 'responsable', '')), ''),
    greatest(coalesce((p_gasto ->> 'montoGravado')::numeric, 0), 0),
    greatest(coalesce((p_gasto ->> 'montoExento')::numeric, 0), 0),
    greatest(least(coalesce((p_gasto ->> 'tasaItbis')::numeric, 18), 100), 0),
    greatest(coalesce((p_gasto ->> 'montoItbis')::numeric, 0), 0),
    greatest(coalesce((p_gasto ->> 'total')::numeric, 0), 0),
    coalesce(nullif(trim(p_gasto ->> 'formaPago'), ''), 'Efectivo'),
    trim(coalesce(p_gasto ->> 'concepto', '')),
    nullif(trim(coalesce(p_gasto ->> 'notas', '')), ''),
    coalesce(nullif(trim(p_gasto ->> 'estadoDgii'), ''), 'Borrador')
  ) returning gastos_menores.id into v_id;

  v_numero_control := format('GME-%s%s', to_char(current_date, 'YY'), lpad(v_id::text, 7, '0'));
  update myappdb.gastos_menores set numero_control = v_numero_control where gastos_menores.id = v_id;

  return query select v_id, v_numero_control;
end;
$$;

revoke all on function myappdb.crear_gasto_menor(jsonb) from public, anon;
grant execute on function myappdb.crear_gasto_menor(jsonb) to authenticated, service_role;

commit;
