begin;

create schema if not exists myappdb;

create table if not exists myappdb.products (
  id integer generated by default as identity primary key,
  codigo text not null,
  descripcion text not null,
  unidad text not null default 'Unidad',
  categoria text not null default 'General',
  ubicacion text,
  marca text,
  tipo text,
  tamano text,
  existencia numeric(14, 2) not null default 0,
  existencia_minima numeric(14, 2) not null default 0,
  costo numeric(14, 2) not null default 0,
  precio_venta numeric(14, 2) not null default 0,
  precio_minimo numeric(14, 2) not null default 0,
  precio_mayor numeric(14, 2) not null default 0,
  cantidad_minima_mayor numeric(14, 2) not null default 0,
  codigo_reemplazo text,
  exento_itbis boolean not null default false,
  valor_impuesto numeric(5, 2) not null default 18,
  estado text not null default 'Activo',
  url_imagen text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint products_codigo_key unique (codigo),
  constraint products_estado_check check (estado in ('Activo', 'Inactivo', 'Agotado'))
);

create index if not exists products_descripcion_idx on myappdb.products (descripcion);
create index if not exists products_categoria_idx on myappdb.products (categoria);
create index if not exists products_estado_idx on myappdb.products (estado);
create index if not exists products_marca_idx on myappdb.products (marca);

create or replace function myappdb.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'products_set_updated_at'
      and tgrelid = 'myappdb.products'::regclass
  ) then
    create trigger products_set_updated_at
    before update on myappdb.products
    for each row
    execute function myappdb.set_updated_at();
  end if;
end;
$$;

alter table myappdb.products enable row level security;

grant usage on schema myappdb to anon, authenticated, service_role;
grant select, insert, update, delete on myappdb.products to anon, authenticated, service_role;
grant usage, select on sequence myappdb.products_id_seq to anon, authenticated, service_role;
grant execute on function myappdb.set_updated_at() to anon, authenticated, service_role;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'products'
      and policyname = 'products_select_local_app'
  ) then
    create policy "products_select_local_app"
    on myappdb.products
    for select
    to anon, authenticated
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'products'
      and policyname = 'products_insert_local_app'
  ) then
    create policy "products_insert_local_app"
    on myappdb.products
    for insert
    to anon, authenticated
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'products'
      and policyname = 'products_update_local_app'
  ) then
    create policy "products_update_local_app"
    on myappdb.products
    for update
    to anon, authenticated
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'myappdb'
      and tablename = 'products'
      and policyname = 'products_delete_local_app'
  ) then
    create policy "products_delete_local_app"
    on myappdb.products
    for delete
    to anon, authenticated
    using (true);
  end if;
end;
$$;

commit;
