begin;

create table if not exists myappdb.compras_606 (
  id bigint generated by default as identity primary key,
  idempres integer not null references myappdb.empresas(id) on delete restrict,
  idsucursal integer not null,
  numero_registro text unique,
  fecha_registro date not null default current_date,
  proveedor_nombre text not null,
  rnc_cedula text not null,
  tipo_identificacion text not null default 'RNC',
  numero_factura text not null,
  ncf text not null,
  fecha_factura date not null,
  fecha_pago date,
  tipo_pago text not null,
  tipo_bien_servicio text not null,
  monto_facturado numeric(14,2) not null check (monto_facturado > 0),
  monto_itbis numeric(14,2) not null default 0 check (monto_itbis >= 0),
  subtotal numeric(14,2) not null default 0 check (subtotal >= 0),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create index if not exists compras_606_empresa_fecha_idx
  on myappdb.compras_606 (idempres, idsucursal, fecha_factura desc);

alter table myappdb.compras_606 enable row level security;

grant select, insert, update, delete on myappdb.compras_606 to authenticated, service_role;
grant usage, select on sequence myappdb.compras_606_id_seq to authenticated, service_role;

create policy compras_606_empresa
on myappdb.compras_606 for all to authenticated
using (
  idempres = (
    select u.empresa_id from myappdb.usuarios u
    where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'
  )
)
with check (
  idempres = (
    select u.empresa_id from myappdb.usuarios u
    where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'
  )
);

create or replace function myappdb.crear_compra_606(p_compra jsonb)
returns table (id bigint, numero_registro text)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_empresa_id integer;
  v_sucursal_id integer;
  v_id bigint;
  v_numero_registro text;
begin
  select u.empresa_id, u.sucursal_id
  into v_empresa_id, v_sucursal_id
  from myappdb.usuarios u
  where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo';

  if v_empresa_id is null or v_sucursal_id is null then
    raise exception 'El usuario no tiene empresa o sucursal activa.' using errcode = '22023';
  end if;

  if trim(coalesce(p_compra ->> 'proveedorNombre', '')) = ''
    or trim(coalesce(p_compra ->> 'rncCedula', '')) = ''
    or trim(coalesce(p_compra ->> 'numeroFactura', '')) = ''
    or trim(coalesce(p_compra ->> 'ncf', '')) = '' then
    raise exception 'Completa el proveedor, RNC/Cédula, número de factura y NCF.' using errcode = '22023';
  end if;

  if coalesce((p_compra ->> 'montoFacturado')::numeric, 0) <= 0 then
    raise exception 'El monto facturado debe ser mayor que cero.' using errcode = '22023';
  end if;

  insert into myappdb.compras_606 (
    idempres, idsucursal, proveedor_nombre, rnc_cedula, tipo_identificacion,
    numero_factura, ncf, fecha_factura, fecha_pago, tipo_pago,
    tipo_bien_servicio, monto_facturado, monto_itbis, subtotal
  ) values (
    v_empresa_id,
    v_sucursal_id,
    trim(p_compra ->> 'proveedorNombre'),
    trim(p_compra ->> 'rncCedula'),
    case when length(regexp_replace(coalesce(p_compra ->> 'rncCedula', ''), '[^0-9]', '', 'g')) = 11 then 'RNC' else 'Cédula' end,
    trim(p_compra ->> 'numeroFactura'),
    trim(p_compra ->> 'ncf'),
    coalesce(nullif(p_compra ->> 'fechaFactura', '')::date, current_date),
    nullif(p_compra ->> 'fechaPago', '')::date,
    coalesce(nullif(trim(p_compra ->> 'tipoPago'), ''), '01 - Efectivo'),
    coalesce(nullif(trim(p_compra ->> 'tipoBienServicio'), ''), '02 - Bienes'),
    (p_compra ->> 'montoFacturado')::numeric,
    greatest(coalesce((p_compra ->> 'montoItbis')::numeric, 0), 0),
    greatest(coalesce((p_compra ->> 'subtotal')::numeric, 0), 0)
  ) returning compras_606.id into v_id;

  v_numero_registro := lpad(v_id::text, 8, '0');
  update myappdb.compras_606
  set numero_registro = v_numero_registro
  where compras_606.id = v_id;

  return query select v_id, v_numero_registro;
end;
$$;

grant execute on function myappdb.crear_compra_606(jsonb) to authenticated, service_role;

commit;
