begin;

create table if not exists myappdb.isr (
  id bigint generated by default as identity primary key,
  porcentaje numeric(5,2) not null unique check (porcentaje between 0 and 100),
  descripcion text not null,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

insert into myappdb.isr (porcentaje, descripcion)
values
  (0, '0% (Sin retención)'),
  (2, '2%'),
  (4, '4%'),
  (10, '10%'),
  (15, '15%')
on conflict (porcentaje) do update
set descripcion = excluded.descripcion,
    activo = true;

alter table myappdb.isr enable row level security;

grant select on myappdb.isr to authenticated;
grant usage, select on sequence myappdb.isr_id_seq to authenticated;

create policy isr_authenticated_read
on myappdb.isr for select to authenticated
using (true);

create table if not exists myappdb.comprobantes_e41 (
  id bigint generated by default as identity primary key,
  idempres integer not null references myappdb.empresas(id) on delete restrict,
  idsucursal smallint not null,
  numero_control text not null,
  fecha_control date not null default current_date,
  encf text not null,
  fecha_emision date not null,
  tipo_compra text not null check (tipo_compra in ('Producto', 'Servicio', 'Mixto')),
  descripcion_operacion text,
  tipo_documento_proveedor text not null,
  numero_documento_proveedor text not null,
  proveedor_nombre text not null,
  monto_compra numeric(14,2) not null check (monto_compra > 0),
  tasa_itbis numeric(5,2) not null default 18 check (tasa_itbis between 0 and 100),
  porcentaje_retencion_itbis numeric(5,2) not null default 0 check (porcentaje_retencion_itbis between 0 and 100),
  porcentaje_retencion_isr numeric(5,2) not null default 0 check (porcentaje_retencion_isr between 0 and 100),
  monto_itbis numeric(14,2) not null default 0 check (monto_itbis >= 0),
  monto_retencion_itbis numeric(14,2) not null default 0 check (monto_retencion_itbis >= 0),
  monto_retencion_isr numeric(14,2) not null default 0 check (monto_retencion_isr >= 0),
  total_pagar numeric(14,2) not null default 0 check (total_pagar >= 0),
  estado_dgii text not null default 'Borrador' check (estado_dgii in ('Borrador', 'Enviado', 'Aceptado', 'Rechazado', 'Error')),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  unique (idempres, numero_control),
  unique (idempres, encf)
);

create index if not exists comprobantes_e41_empresa_fecha_idx
  on myappdb.comprobantes_e41 (idempres, fecha_control desc, id desc);

alter table myappdb.comprobantes_e41 enable row level security;

grant select, insert, update, delete on myappdb.comprobantes_e41 to authenticated;
grant usage, select on sequence myappdb.comprobantes_e41_id_seq to authenticated;

create policy comprobantes_e41_tenant_access
on myappdb.comprobantes_e41 for all to authenticated
using (idempres = (select private.current_empresa_id()))
with check (idempres = (select private.current_empresa_id()));

create or replace function myappdb.crear_comprobante_e41(p_comprobante jsonb)
returns table (id bigint, numero_control text, encf text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_empresa_id integer;
  v_sucursal_id integer;
  v_id bigint;
  v_numero_control text;
  v_encf text;
  v_monto_compra numeric(14,2);
  v_tasa_itbis numeric(5,2);
  v_retencion_itbis numeric(5,2);
  v_retencion_isr numeric(5,2);
  v_monto_itbis numeric(14,2);
  v_monto_retencion_itbis numeric(14,2);
  v_monto_retencion_isr numeric(14,2);
  v_total_pagar numeric(14,2);
begin
  select u.empresa_id, u.sucursal_id
  into v_empresa_id, v_sucursal_id
  from myappdb.usuarios u
  where u.auth_usuario_id = (select auth.uid())
    and u.estado = 'Activo';

  if v_empresa_id is null or v_sucursal_id is null then
    raise exception 'El usuario no tiene empresa o sucursal activa.' using errcode = '22023';
  end if;

  if trim(coalesce(p_comprobante ->> 'numeroDocumentoProveedor', '')) = ''
    or trim(coalesce(p_comprobante ->> 'proveedorNombre', '')) = '' then
    raise exception 'Completa el documento y el nombre del proveedor.' using errcode = '22023';
  end if;

  v_monto_compra := greatest(coalesce(nullif(p_comprobante ->> 'montoCompra', '')::numeric, 0), 0);
  if v_monto_compra <= 0 then
    raise exception 'El monto de compra debe ser mayor que cero.' using errcode = '22023';
  end if;

  v_tasa_itbis := greatest(least(coalesce(nullif(p_comprobante ->> 'tasaItbis', '')::numeric, 18), 100), 0);
  v_retencion_itbis := greatest(least(coalesce(nullif(p_comprobante ->> 'retencionItbis', '')::numeric, 0), 100), 0);
  v_retencion_isr := greatest(least(coalesce(nullif(p_comprobante ->> 'retencionIsr', '')::numeric, 0), 100), 0);
  v_monto_itbis := round(v_monto_compra * v_tasa_itbis / 100, 2);
  v_monto_retencion_itbis := round(v_monto_itbis * v_retencion_itbis / 100, 2);
  v_monto_retencion_isr := round(v_monto_compra * v_retencion_isr / 100, 2);
  v_total_pagar := round(v_monto_compra + v_monto_itbis - v_monto_retencion_itbis - v_monto_retencion_isr, 2);

  select s.encf
  into v_encf
  from myappdb.siguiente_encf_desde_secuencia_ncf_con_vencimiento(v_empresa_id, 'E41') s;

  insert into myappdb.comprobantes_e41 (
    idempres, idsucursal, numero_control, encf, fecha_emision, tipo_compra,
    descripcion_operacion, tipo_documento_proveedor, numero_documento_proveedor,
    proveedor_nombre, monto_compra, tasa_itbis, porcentaje_retencion_itbis,
    porcentaje_retencion_isr, monto_itbis, monto_retencion_itbis,
    monto_retencion_isr, total_pagar, estado_dgii
  ) values (
    v_empresa_id, v_sucursal_id, 'PENDIENTE', v_encf,
    coalesce(nullif(p_comprobante ->> 'fechaEmision', '')::date, current_date),
    coalesce(nullif(trim(p_comprobante ->> 'tipoCompra'), ''), 'Producto'),
    nullif(trim(p_comprobante ->> 'descripcionOperacion'), ''),
    coalesce(nullif(trim(p_comprobante ->> 'tipoDocumentoProveedor'), ''), 'Cédula'),
    trim(p_comprobante ->> 'numeroDocumentoProveedor'),
    trim(p_comprobante ->> 'proveedorNombre'),
    v_monto_compra, v_tasa_itbis, v_retencion_itbis, v_retencion_isr,
    v_monto_itbis, v_monto_retencion_itbis, v_monto_retencion_isr,
    v_total_pagar,
    case when p_comprobante ->> 'estadoDgii' = 'Enviado' then 'Enviado' else 'Borrador' end
  ) returning comprobantes_e41.id into v_id;

  v_numero_control := lpad(v_id::text, 8, '0');
  update myappdb.comprobantes_e41
  set numero_control = v_numero_control
  where comprobantes_e41.id = v_id;

  return query select v_id, v_numero_control, v_encf;
end;
$$;

revoke all on function myappdb.crear_comprobante_e41(jsonb) from public, anon;
grant execute on function myappdb.crear_comprobante_e41(jsonb) to authenticated;

create or replace function myappdb.actualizar_comprobante_e41(
  p_id bigint,
  p_comprobante jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_empresa_id integer;
  v_monto_compra numeric(14,2);
  v_tasa_itbis numeric(5,2);
  v_retencion_itbis numeric(5,2);
  v_retencion_isr numeric(5,2);
  v_monto_itbis numeric(14,2);
  v_monto_retencion_itbis numeric(14,2);
  v_monto_retencion_isr numeric(14,2);
  v_total_pagar numeric(14,2);
begin
  select u.empresa_id into v_empresa_id
  from myappdb.usuarios u
  where u.auth_usuario_id = (select auth.uid())
    and u.estado = 'Activo';

  if v_empresa_id is null then
    raise exception 'El usuario no tiene una empresa activa.' using errcode = '22023';
  end if;

  if not exists (
    select 1 from myappdb.comprobantes_e41 c
    where c.id = p_id and c.idempres = v_empresa_id and c.estado_dgii <> 'Aceptado'
  ) then
    raise exception 'El comprobante no existe, no pertenece a la empresa activa o ya fue aceptado.' using errcode = '22023';
  end if;

  if trim(coalesce(p_comprobante ->> 'numeroDocumentoProveedor', '')) = ''
    or trim(coalesce(p_comprobante ->> 'proveedorNombre', '')) = '' then
    raise exception 'Completa el documento y el nombre del proveedor.' using errcode = '22023';
  end if;

  v_monto_compra := greatest(coalesce(nullif(p_comprobante ->> 'montoCompra', '')::numeric, 0), 0);
  if v_monto_compra <= 0 then
    raise exception 'El monto de compra debe ser mayor que cero.' using errcode = '22023';
  end if;

  v_tasa_itbis := greatest(least(coalesce(nullif(p_comprobante ->> 'tasaItbis', '')::numeric, 18), 100), 0);
  v_retencion_itbis := greatest(least(coalesce(nullif(p_comprobante ->> 'retencionItbis', '')::numeric, 0), 100), 0);
  v_retencion_isr := greatest(least(coalesce(nullif(p_comprobante ->> 'retencionIsr', '')::numeric, 0), 100), 0);
  v_monto_itbis := round(v_monto_compra * v_tasa_itbis / 100, 2);
  v_monto_retencion_itbis := round(v_monto_itbis * v_retencion_itbis / 100, 2);
  v_monto_retencion_isr := round(v_monto_compra * v_retencion_isr / 100, 2);
  v_total_pagar := round(v_monto_compra + v_monto_itbis - v_monto_retencion_itbis - v_monto_retencion_isr, 2);

  update myappdb.comprobantes_e41
  set fecha_emision = coalesce(nullif(p_comprobante ->> 'fechaEmision', '')::date, fecha_emision),
      tipo_compra = coalesce(nullif(trim(p_comprobante ->> 'tipoCompra'), ''), tipo_compra),
      descripcion_operacion = nullif(trim(p_comprobante ->> 'descripcionOperacion'), ''),
      tipo_documento_proveedor = coalesce(nullif(trim(p_comprobante ->> 'tipoDocumentoProveedor'), ''), tipo_documento_proveedor),
      numero_documento_proveedor = trim(p_comprobante ->> 'numeroDocumentoProveedor'),
      proveedor_nombre = trim(p_comprobante ->> 'proveedorNombre'),
      monto_compra = v_monto_compra,
      tasa_itbis = v_tasa_itbis,
      porcentaje_retencion_itbis = v_retencion_itbis,
      porcentaje_retencion_isr = v_retencion_isr,
      monto_itbis = v_monto_itbis,
      monto_retencion_itbis = v_monto_retencion_itbis,
      monto_retencion_isr = v_monto_retencion_isr,
      total_pagar = v_total_pagar,
      estado_dgii = case when p_comprobante ->> 'estadoDgii' = 'Enviado' then 'Enviado' else 'Borrador' end,
      actualizado_en = now()
  where id = p_id and idempres = v_empresa_id;
end;
$$;

revoke all on function myappdb.actualizar_comprobante_e41(bigint, jsonb) from public, anon;
grant execute on function myappdb.actualizar_comprobante_e41(bigint, jsonb) to authenticated;

commit;
