begin;

create table if not exists myappdb.notas_credito (
  id bigint generated by default as identity primary key,
  idempres integer not null references myappdb.empresas(id) on delete restrict,
  idsucursal bigint not null references myappdb.sucursales(idsucursal) on delete restrict,
  factura_afectada_id bigint references myappdb.facturas(id) on delete restrict,
  numero_nota text not null unique,
  numero_factura_afectada text not null,
  encf_afectado text not null,
  fecha_comprobante_afectado date,
  cliente_rnc text,
  cliente_nombre text,
  cliente_correo text,
  cliente_direccion text,
  encf_nota text,
  fecha_emision date not null default current_date,
  fecha_vencimiento_secuencia date,
  codigo_modificacion text not null,
  tipo_ingreso text not null,
  forma_pago text not null default 'Contado',
  motivo text not null,
  notas_internas text,
  subtotal numeric(14, 2) not null default 0,
  descuentos numeric(14, 2) not null default 0,
  itbis numeric(14, 2) not null default 0,
  total numeric(14, 2) not null default 0,
  estado_dgii text not null default 'Sin enviar',
  dgii_track_id text,
  dgii_codigo_seguridad text,
  dgii_codigo text,
  dgii_mensajes jsonb,
  dgii_request_json jsonb,
  dgii_response_json jsonb,
  dgii_response_raw text,
  dgii_error_message text,
  dgii_updated_at timestamptz,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint notas_credito_totales_check check (subtotal >= 0 and descuentos >= 0 and itbis >= 0 and total >= 0),
  constraint notas_credito_estado_dgii_check check (estado_dgii in ('Sin enviar', 'Enviado', 'Aceptado', 'Aceptado condicional', 'Rechazado', 'Error'))
);

create table if not exists myappdb.nota_credito_detalles (
  id bigint generated by default as identity primary key,
  nota_credito_id bigint not null references myappdb.notas_credito(id) on delete cascade,
  descripcion text not null,
  cantidad numeric(14, 2) not null,
  precio_unitario numeric(14, 2) not null,
  descuento_porcentaje numeric(5, 2) not null default 0,
  tasa_itbis numeric(5, 2) not null default 0,
  monto_itbis numeric(14, 2) not null default 0,
  total_linea numeric(14, 2) not null,
  creado_en timestamptz not null default now(),
  constraint nota_credito_detalles_cantidad_check check (cantidad > 0),
  constraint nota_credito_detalles_precio_check check (precio_unitario >= 0),
  constraint nota_credito_detalles_descuento_check check (descuento_porcentaje between 0 and 100),
  constraint nota_credito_detalles_itbis_check check (tasa_itbis between 0 and 100),
  constraint nota_credito_detalles_total_check check (monto_itbis >= 0 and total_linea >= 0)
);

create index if not exists notas_credito_empresa_fecha_idx on myappdb.notas_credito (idempres, idsucursal, fecha_emision desc);
create index if not exists notas_credito_factura_afectada_idx on myappdb.notas_credito (factura_afectada_id);
create index if not exists nota_credito_detalles_nota_idx on myappdb.nota_credito_detalles (nota_credito_id);

drop trigger if exists notas_credito_set_updated_at on myappdb.notas_credito;
create trigger notas_credito_set_updated_at
before update on myappdb.notas_credito
for each row execute function myappdb.set_updated_at();

alter table myappdb.notas_credito enable row level security;
alter table myappdb.nota_credito_detalles enable row level security;

grant select, insert, update on myappdb.notas_credito to authenticated, service_role;
grant select, insert, update on myappdb.nota_credito_detalles to authenticated, service_role;
grant select, insert, update on myappdb.contador_doc to authenticated, service_role;
grant usage, select on sequence myappdb.notas_credito_id_seq to authenticated, service_role;
grant usage, select on sequence myappdb.nota_credito_detalles_id_seq to authenticated, service_role;

create policy notas_credito_select_empresa on myappdb.notas_credito
for select to authenticated
using (idempres = (select u.empresa_id from myappdb.usuarios u where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'));

create policy notas_credito_insert_empresa on myappdb.notas_credito
for insert to authenticated
with check (idempres = (select u.empresa_id from myappdb.usuarios u where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'));

create policy notas_credito_update_empresa on myappdb.notas_credito
for update to authenticated
using (idempres = (select u.empresa_id from myappdb.usuarios u where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'))
with check (idempres = (select u.empresa_id from myappdb.usuarios u where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'));

create policy nota_credito_detalles_select_empresa on myappdb.nota_credito_detalles
for select to authenticated
using (exists (select 1 from myappdb.notas_credito n where n.id = nota_credito_id));

create policy nota_credito_detalles_insert_empresa on myappdb.nota_credito_detalles
for insert to authenticated
with check (exists (select 1 from myappdb.notas_credito n where n.id = nota_credito_id));

create policy contador_doc_select_empresa on myappdb.contador_doc
for select to authenticated
using (id_empres = (select u.empresa_id from myappdb.usuarios u where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'));

create policy contador_doc_insert_empresa on myappdb.contador_doc
for insert to authenticated
with check (id_empres = (select u.empresa_id from myappdb.usuarios u where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'));

create policy contador_doc_update_empresa on myappdb.contador_doc
for update to authenticated
using (id_empres = (select u.empresa_id from myappdb.usuarios u where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'))
with check (id_empres = (select u.empresa_id from myappdb.usuarios u where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo'));

create or replace function myappdb.crear_nota_credito(p_nota jsonb, p_detalles jsonb)
returns table (id bigint, numero_nota text)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  empresa_usuario_id integer;
  sucursal_usuario_id bigint;
  consecutivo integer;
  nueva_nota_id bigint;
  nuevo_numero_nota text;
begin
  if jsonb_array_length(coalesce(p_detalles, '[]'::jsonb)) = 0 then
    raise exception 'La nota de crédito debe incluir al menos una línea.' using errcode = '22023';
  end if;

  select u.empresa_id, u.sucursal_id
  into empresa_usuario_id, sucursal_usuario_id
  from myappdb.usuarios u
  where u.auth_usuario_id = (select auth.uid()) and u.estado = 'Activo';

  if not found or sucursal_usuario_id is null then
    raise exception 'No se encontró un usuario activo con empresa y sucursal asignadas.' using errcode = '42501';
  end if;

  insert into myappdb.contador_doc (id_empres, nom_empresa, ano, factura, cotizacion, nota_credito, gasto_menores, recibo, sucursal_id)
  select e.id, e.nombre_comercial, extract(year from current_date)::smallint, 0, 0, 0, 0, 0, sucursal_usuario_id::smallint
  from myappdb.empresas e where e.id = empresa_usuario_id
  on conflict (id_empres, ano, sucursal_id) do nothing;

  update myappdb.contador_doc
  set nota_credito = nota_credito + 1
  where id_empres = empresa_usuario_id
    and sucursal_id = sucursal_usuario_id::smallint
    and ano = extract(year from current_date)::smallint
  returning nota_credito into consecutivo;

  if not found then
    raise exception 'No se pudo actualizar el contador de nota de crédito.' using errcode = '23503';
  end if;

  nuevo_numero_nota := extract(year from current_date)::text || lpad(sucursal_usuario_id::text, 2, '0') || lpad(consecutivo::text, 5, '0');

  insert into myappdb.notas_credito (
    idempres, idsucursal, factura_afectada_id, numero_nota, numero_factura_afectada, encf_afectado,
    fecha_comprobante_afectado, cliente_rnc, cliente_nombre, cliente_correo, cliente_direccion,
    encf_nota, fecha_emision, fecha_vencimiento_secuencia, codigo_modificacion, tipo_ingreso,
    forma_pago, motivo, notas_internas, subtotal, descuentos, itbis, total
  ) values (
    empresa_usuario_id, sucursal_usuario_id, nullif(p_nota ->> 'invoiceId', '')::bigint,
    nuevo_numero_nota, p_nota ->> 'invoice', p_nota ->> 'encfAffected',
    nullif(p_nota ->> 'affectedDate', '')::date, nullif(p_nota ->> 'rnc', ''), nullif(p_nota ->> 'customer', ''),
    nullif(p_nota ->> 'email', ''), nullif(p_nota ->> 'address', ''), nullif(p_nota ->> 'noteEncf', ''),
    coalesce(nullif(p_nota ->> 'date', '')::date, current_date), nullif(p_nota ->> 'expiry', '')::date,
    p_nota ->> 'modificationCode', p_nota ->> 'incomeType', coalesce(nullif(p_nota ->> 'payment', ''), 'Contado'),
    p_nota ->> 'reason', nullif(p_nota ->> 'internalNotes', ''),
    coalesce((p_nota ->> 'subtotal')::numeric, 0), coalesce((p_nota ->> 'discounts')::numeric, 0),
    coalesce((p_nota ->> 'itbis')::numeric, 0), coalesce((p_nota ->> 'total')::numeric, 0)
  ) returning notas_credito.id, notas_credito.numero_nota into nueva_nota_id, nuevo_numero_nota;

  insert into myappdb.nota_credito_detalles (
    nota_credito_id, descripcion, cantidad, precio_unitario, descuento_porcentaje, tasa_itbis, monto_itbis, total_linea
  )
  select nueva_nota_id, detalle ->> 'description', (detalle ->> 'quantity')::numeric,
    (detalle ->> 'price')::numeric, coalesce((detalle ->> 'discount')::numeric, 0),
    coalesce((detalle ->> 'itbis')::numeric, 0), coalesce((detalle ->> 'taxAmount')::numeric, 0),
    (detalle ->> 'lineTotal')::numeric
  from jsonb_array_elements(p_detalles) detalle;

  return query select nueva_nota_id, nuevo_numero_nota;
end;
$$;

grant execute on function myappdb.crear_nota_credito(jsonb, jsonb) to authenticated, service_role;

commit;
